---
all:
  vars:
    ansible_host: localhost
    ansible_user: vagrant
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    kmachine:
      ansible_host: localhost
      ansible_user: vagrant
      ansible_port: 2222
      ansible_private_key_file: .vagrant/machines/default/virtualbox/private_key
      ansible_python_interpreter: /usr/bin/python3
    k3s-master:
      ansible_connection: lxd
      ansible_host: vagrant:k3s-master
    k3s-worker:
      ansible_connection: lxd
      ansible_host: vagrant:k3s-worker
    knodes:
      hosts:
        k3s-master:
        k3s-worker:
