- hosts: localhost
  connection: local
  tasks:
    - name: Create a started container
      lxd_container:
        name: container
        url: https://192.168.33.10:8443
        trust_password: Admin2193!
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: lxd
          alias: ubuntu/xenial/amd64
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
    - name: check python is installed in container
      remote_user: root
      delegate_to: container 
      raw: dpkg -s python
      register: python_install_check
      failed_when: python_install_check.rc not in [0, 1]
      changed_when: false

    - name: install python in container
      remote_user: root
      delegate_to: container 
      raw: apt-get install -y python
      when: python_install_check.rc == 1
  # - name: Enable LLMNR
  #
  #
  #   replace:
  #     dest: /etc/systemd/resolved.conf
  #     regexp: '#LLMNR=no'
  #     replace: 'LLMNR=yes'
  #   register: resolvedconf
  # - name: Restart systemd-resolved
  #   when: resolvedconf.changed
  #   systemd:
  #     name: systemd-resolved
  #     state: restarted
