---
all_nodes:
  - {ip: '192.168.33.10', name: 'kmachine', fqdn: 'kmachine'}

basic_apps:
  - curl
  - mtr-tiny
  - zfsutils-linux
  # - bridge-utils
  - socat
  - jq
  - dnsutils
  - build-essential
  - ntp
  - acl
  - htop
  - httpie
  - vim
  - wget
  - dirmngr
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - libpq-dev
  - python-dev
  - python-pip
  - python-pycurl
  - supervisor
  - unzip
  - openssl
  - libssl-dev
  - libssl-doc

  # for nfs mounting and unmounting.
  - nfs-common

ntp_enabled: true
default_timezone: America/Chicago
ntp_timezone: "{{ default_timezone }}"

k3s_version: v0.5.0
systemd_dir: /etc/systemd/system

k3s_flannel_deploy: no
k3s_traefik_deploy: no
k3s_flannel_iface: enp0s8
k3s_flannel_iface_key: ansible_{{ k3s_flannel_iface }}
# master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
master_ip: 192.168.33.10